<?php


    use Drupal\Core\Routing\RouteMatchInterface;


    function kimulator_help($route_name, RouteMatchInterface $route_match) {
        if($route_name == 'help.page.kimulator')
        return '<p>' . t('Ki Help Page KImulator.') . '</p>';  
    } 






    function getAPIResponse($prompt, $endpoint, $api_key, $option, $option_aimodel) {

        // Initialisiere die cURL-Sitzung
        $ch = curl_init($endpoint);

        // Setze cURL-Optionen
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            "Authorization: Bearer $api_key",
            "Content-Type: application/json"
        ));

        // Nutzlast für den Chat-Eingang unter Verwendung der Nachrichtenstruktur
        // gpt-4o-mini
        // billig: gpt-4.1-nano 
        $data = array(
            'model' => $option_aimodel,            
            'messages' => array(
                array('role' => 'system', 'content' => 'Sie sind ein hilfreicher A.'),
                array('role' => 'user', 'content' => $prompt)
            )
            /*
            'input' => 'porttraitfoto von klimaforscher, comic art',
            'tools' => array(
                array('type' => 'image_generation')
            )
            */
        );


        $data_string = json_encode($data);

        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);

        // Führe die cURL-Sitzung aus
        $response = curl_exec($ch);

        // Überprüfe auf cURL-Fehler
        if(curl_errno($ch)){
            echo 'Curl-Fehler: ' . curl_error($ch);
            exit;
        }

        // Dekodiere die Antwort
        $response_data = json_decode($response, true);

        // Überprüfe, ob der Schlüssel 'choices' in der Antwort vorhanden ist und ob der Nachrichteninhalt vorhanden ist
        if (!isset($response_data['choices']) || !isset($response_data['choices'][0]['message']['content'])) {
            echo "Fehler: Unerwartete API-Antwort.<br>";
            echo "Vollständige Antwort:<br>";
            print_r($response_data);
            exit;
        }

        // Hole die Antwort aus der API-Antwort
        $answer = $response_data['choices'][0]['message']['content'];

        // Close cURL-Sitzung
        curl_close($ch);
       
        return $answer; 
    }




    

   
